server:
  port: 8762


info:
  app:
    name: Zuul Proxy
    description: Zuul Proxy spring boot application
    version: 1.0.0

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    logfile:
      external-file: /tmp/zuul.log      
security:
  basic:
    enabled: false

spring.security.user.name: test
spring.security.user.password: test

spring:
  zipkin:
    base-url: http://zipkin-server
    locator:
      discovery:
        enabled: true
  sleuth:
    web:
      skip-pattern: 
    sampler:
      probability: 1.0   
      
---
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}      

---

spring:
  profiles: cloud
  

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}/eureka        