server:
  port: 8762



info:
  app:
    name: Zuul Proxy
    description: Zuul Proxy spring boot application
    version: 1.0.0

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
security:
  basic:
    enabled: false

spring:
  application:
    admin:
      enabled: true
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
---
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
      

---

spring:
  profiles: cloud
  

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}/eureka