server:
  port: 8762

management:
  security:
    enabled: false
security:
  basic:
    enabled: false

spring:
  application:
    admin:
      enabled: false
  

---
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
      

---

spring:
  profiles: cloud
  

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}/eureka  
      
zuul:
  routes:
    microservice: 
      path: /batterycommon/**
      serviceId: batterycommon